### ISSUE TITLE
When a table is missing the error message is pretty cryptic

### ISSUE THREAD

**Issue by visheshd** [benhutchins/dyngoose#398]
Currently, if the table is missing there is the following stack trace

(node:61045) UnhandledPromiseRejectionWarning: ResourceNotFoundException: Requested resource not found
    at Request.extractError (/project/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.callListeners (/project/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/project/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/project/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/project/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/project/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /project/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/project/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/project/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/project/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at Request.emit (/project/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/project/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/project/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/project/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /project/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/project/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/project/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/project/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at callNextListener (/project/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at IncomingMessage.onEnd (/project/node_modules/aws-sdk/lib/event_listeners.js:307:13)
    at IncomingMessage.emit (events.js:327:22)
    at IncomingMessage.EventEmitter.emit (domain.js:483:12)
(node:61045) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:61045) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by benhutchins** [comment]
I've had this same problem. Any error thrown when performing a query, the AWSError object's stack trace is so large you can't find what query caused the error from your own code.

I think I'll address this.

**Comment by benhutchins** [comment]
The unhandled promise part is from your code, if you wrap Dyngoose calls with a try-catch you can catch the errors and try to handle the situation.

**Comment by visheshd** [comment]
Thanks, yes could be handled outside but would be neat to have it in a central place like the library.

**Comment by benhutchins** [comment]
I've addressed this as part of b7c5f05.

> feat: throw helpful errors with useful stacks
> 
> Errors still inherit and confirm to the AWSError object, but include an
> abbreviated stack trace that terminates at the Dyngoose methods. Errors
> also now includes the table name, table class object, and the query
> or scan input called for diagnostics. The query input is not included
> in the error message, as that can easily lead to security concerns, but
> including it on the error object might prove helpful when debugging
> tricky query issues.
